# ##################################
# Treatlife 3-Way Light Switch
# ##################################
# D2 GPIO04: white led (inverted)
# D1 GPIO05: red led (inverted)
# D6 GPIO12: relay
# D7 GPIO13: button (inverted)
# D5 GPIO14: power/usage sensor (inverted)
# ##################################


substitutions:
  device_name: treatlife_3_way_light_switch
  friendly_name: Treatlife 3 Way Light Switch
  icon: "mdi:light-switch"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret esphome_ap_password

captive_portal:

logger:

api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

status_led:
  pin:
    number: GPIO5   # Red LED
    inverted: True

binary_sensor:
- platform: gpio
  id: power_sensor
  pin:
    number: GPIO14
    inverted: True
  filters:
    - delayed_off: 50ms
  on_press:
    - light.turn_off: white_led
  on_release:
    - light.turn_on: white_led
  internal: True

- platform: gpio
  pin:
    number: GPIO13
    inverted: True
  id: button
  on_multi_click:
  # Single Click:
  - timing:
    - ON for at most 1s
    - OFF for at least 0.3s
    then:
      - switch.toggle: ${device_name}
      - logger.log: "Single Short Clicked"
      - homeassistant.event:
          event: esphome.${device_name}
          data:
            title: single_click 
  # Double Click:
  - timing:
    - ON for at most 1s
    - OFF for at most 1s
    - ON for at most 1s
    - OFF for at least 0.2s
    then:
      - logger.log: "Double Clicked"
      - homeassistant.event:
          event: esphome.${device_name}
          data:
            title: double_click
  # Long Press:
  - timing:
    - ON for 1s to 2s
    - OFF for at least 0.3s
    then:
      - logger.log: "Single Long Press"
      - homeassistant.event:
          event: esphome.${device_name}
          data:
            title: long_press
  - timing:
    - ON for at least 2.2s
    then:
      - logger.log: "Press and Hold"
      - homeassistant.event:
          event: esphome.${device_name}
          data:
            title: hold
  internal: True

light:
- platform: binary
  id: white_led
  output: led_1
  restore_mode: RESTORE_DEFAULT_ON
  internal: True
 
output:
- platform: gpio
  id: led_1
  pin:
    number: GPIO4
    inverted: True

switch:
- platform: gpio
  id: red_led
  pin:
    number: GPIO5
    inverted: True
  internal: True

- platform: restart
  name: ${friendly_name} REBOOT

- platform: gpio
  pin: GPIO12
  id: relay
  restore_mode: RESTORE_DEFAULT_OFF
  internal: True

- platform: template
  name: ${friendly_name}
  id: ${device_name}
  icon: ${icon}
  lambda: |-
    if (id(power_sensor).state) {
      return true;
    } else {
      return false;
    }
  turn_on_action:
  - if:
      condition:
      - binary_sensor.is_off: power_sensor
      then:
      - switch.toggle: relay
  turn_off_action:
  - if:
      condition:
      - binary_sensor.is_on: power_sensor
      then:
      - switch.toggle: relay
