# ##################################
# Treatlife Light Switch
# ##################################
# D2 GPIO04: white led (inverted) (sensor)
# D1 GPIO05: red led (inverted)
# D6 GPIO12: relay
# D7 GPIO13: button (inverted)
# ##################################


substitutions:
  device_name: treatlife_light_switch
  friendly_name: Treatlife Light Switch
  icon: "mdi:light-switch"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret esphome_ap_password
  
captive_portal:

logger:

api:
  password: !secret esphome_api_password
  
ota:
  password: !secret esphome_ota_password

status_led:
  pin:
    number: GPIO5   # Red LED
    inverted: True

binary_sensor:
- platform: gpio
  pin:
    number: GPIO4
    inverted: True
  id: sensor
  internal: True

- platform: gpio
  pin:
    number: GPIO13
    inverted: True
  id: button
  name: ${friendly_name} Button
  on_press:
    - switch.toggle: ${device_name}
  internal: True

light:
- platform: binary
  id: white_led
  output: led_1
  restore_mode: RESTORE_DEFAULT_ON
  internal: True

output:
- platform: gpio
  id: led_1
  pin:
    number: GPIO4
    inverted: True

switch:
- platform: gpio
  id: relay
  pin:
    number: GPIO12
  restore_mode: RESTORE_DEFAULT_OFF
  internal: True

- platform: restart
  name: ${friendly_name} REBOOT

- platform: template
  name: ${friendly_name}
  id: ${device_name}
  icon: ${icon}
  lambda: |-
    if (id(sensor).state) {
      return false;
    } else {
      return true;
    }
  turn_on_action:
  - if:
      condition:
      - binary_sensor.is_on: sensor
      then:
      - switch.turn_on: relay
      - light.turn_off: white_led
  turn_off_action:
  - if:
      condition:
      - binary_sensor.is_off: sensor
      then:
      - switch.turn_off: relay
      - light.turn_on: white_led
